### Login
POST http://localhost:8080/auth/login
content-type: application/json

{
  "email": "admin1@test.com",
  "password": "pass_1234"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.global.set("accessToken", response.body.accessToken);
    client.global.set("refreshToken", response.body.refreshToken);
%}

### Login
POST http://localhost:8080/auth/refresh-token
content-type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

### Authors list
GET http://localhost:8080/api/authors
content-type: application/json
Authorization: Bearer {{accessToken}}

### Books list
GET http://localhost:8080/api/books
content-type: application/json
Authorization: Bearer {{accessToken}}