jwt:
  secret: your-secret-key
spring:
  data:
    rest:
      basePath: /api
  datasource:
    url: jdbc:postgresql://database:5432/mydatabase
    driver-class-name: org.postgresql.Driver
    username: myuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: t